### ISSUE TITLE
[Question] Average retention in the add-on doesn't match average retrievability in beta

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs4anki-helper#260]
**Research**

*Enter an [x] character to confirm the points below:*

- [x] I have checked the [FAQ](https://github.com/open-spaced-repetition/fsrs4anki/wiki/FAQ) and could not find an answer to my question
- [x] I have read the [wiki](https://github.com/open-spaced-repetition/fsrs4anki/wiki) and still felt confused
- [x] I have searched for similar existing questions here

**Question**
Here's the average retention for one of my decks:
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/83031600/e5216cc3-86dd-4b15-834b-f6a02938429f)
And here's the average retrievability from the stats window in 23.10beta4:
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/83031600/d9b7b331-3c36-442a-91df-7b87770ca871)
I assume this is because Anki first bins R, and then calculates and imprecise average based on bins? Or is there some other reason?
EDIT: I think the add-on uses the old DSR values from Custom Data, not the new DSR values in the beta.
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/83031600/5b9d5c3b-1f7b-42ef-9d9b-d88217803d3b)

**Comment by L-M-Sherlock** [comment]
It should be fixed by #238

**Comment by Expertium** [comment]
It seems that it's still a problem in 23.10.1. I have just updated the add-on.
![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/83031600/1c6028ea-b423-4cdf-8081-d88574a0dd46)

**Comment by L-M-Sherlock** [comment]
Thanks for report. I find out a bug:

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/5cb1547a-5125-4f38-87f3-f83f59fc4bad)

@dae, this card's retrievability is incorrect. The last revlog should be ignore. I guess the `elapsed_days` is miscalculated here.

**Comment by L-M-Sherlock** [comment]
https://github.com/ankitects/anki/blob/24e59124480944125eb0c7a325a9cabf760bf782/rslib/src/storage/revlog/time_of_last_review.sql#L4

```sql
SELECT id / 1000
FROM revlog
WHERE cid = $1
  AND ease BETWEEN 1 AND 4
ORDER BY id DESC
LIMIT 1
```

The query doesn't ignore the filtered revlog.

I think the correct query should be:

```sql
SELECT id / 1000
FROM revlog
WHERE cid = $1
  AND ease BETWEEN 1 AND 4
  AND (type != 3 OR factor != 0)
ORDER BY id DESC
LIMIT 1
```

**Comment by Expertium** [comment]
@L-M-Sherlock according to this user the problem still persists: https://forums.ankiweb.net/t/anki-23-12-beta/37771/107?u=expertium

**Comment by dae** [comment]
https://github.com/ankitects/anki/commit/129157eb216893e643acece1759c8045fecd7e72
